name: Install python from pyproject.toml
description: Installs Python from the version found in pyproject.toml

inputs:
 pyproject-file-path:
   required: false
   description: Path to the pyproject.toml including filename
   default: ./pyproject.toml

runs:
 using: composite
 steps:
   - name: Read requires-python from pyproject.toml
     id: get_python_version
     shell: bash
     run: |
       python -c "import tomllib, pathlib; p = pathlib.Path('${{ inputs.pyproject-file-path }}'); req = tomllib.loads(p.read_text())['project']['requires-python']; print(f'result={req}')" >> $GITHUB_OUTPUT

   - name: Set up Python
     uses: actions/setup-python@v5.6.0
     with:
       python-version: ${{ steps.get_python_version.outputs.result }}