name: mkdocs-generation
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material[imaging]
      - run: pip install mkdocs-material-extensions
      - run: pip install pillow cairosvg
      - run: pip install mkdocs-gen-files
      - run: pip install mkdocstrings[python]
      - name: Install package
        run: pip install -e .
      - run: mkdocs gh-deploy --force
